<?php


namespace App\Command;


use App\Service\DataPuller;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class PullDataCommand extends Command
{
    protected static $defaultName = 'app:pull-data';

    /**
     * @var DataPuller
     */
    private $dataPuller;

    public function __construct(DataPuller $dataPuller, string $name = null)
    {
        parent::__construct($name);
        $this->dataPuller = $dataPuller;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('Pulling data');
        $data = $this->dataPuller->pull();
        $output->writeln('Data pulled');
        $output->writeln('Validating data');
        if ($this->dataPuller->isValidData($data)) {
            $output->writeln('Data valid');
            $output->writeln('Backing up data to file');
            $this->dataPuller->backupData($data);
            $output->writeln('Data backed up to file');
            $output->writeln('Refreshing database');
            $this->dataPuller->refreshDatabase($data);
            $output->writeln('Database refreshed');
        } else {
            $output->writeln('Data validation failed');
        }
        $output->writeln('Process completed');

        return 0;
    }
}